# Generated by Django 4.1.2 on 2023-06-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="gender",
            field=models.CharField(max_length=30, null=True, verbose_name="性别"),
        ),
    ]
