# Generated by Django 4.1.2 on 2023-06-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_alter_account_uid_alter_email_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="uid",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="用户ID"
            ),
        ),
    ]
