// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/models/global';
import model_2 from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi-production/plugin-initialState/@@initialState';

export const models = {
model_1: { namespace: 'global', model: model_1 },
model_2: { namespace: '@@initialState', model: model_2 },
} as const
