// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/node_modules/.pnpm/@umijs+renderer-react@4.0.70_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/node_modules/.pnpm/@umijs+renderer-react@4.0.70_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/node_modules/.pnpm/umi@4.0.70_@babel+core@7.22.1_@types+react@18.2.8_eslint@8.35.0_postcss@8.4.24_prettier@2.8.8_o5evzy3wyifw7qx6bsngq3c5ji/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi/plugin-access';
export { Provider, useModel } from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi/plugin-request';
// plugins types.d.ts
export * from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi/plugin-access/types.d';
export * from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi/plugin-antd/types.d';
export * from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi/plugin-layout/types.d';
export * from 'D:/Disk_D/LearningTree/Project/COMP3070/git/GitHub/software/forward/vcat_1_3/vcat_1_1/src/.umi/plugin-request/types.d';
