# Generated by Django 4.1.2 on 2023-06-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetsInfo",
            fields=[
                (
                    "pet_id",
                    models.IntegerField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        verbose_name="宠物ID",
                    ),
                ),
                ("pet_name", models.CharField(max_length=24, verbose_name="宠物名称")),
                ("pet_type", models.CharField(max_length=254, verbose_name="宠物类型")),
                ("level", models.IntegerField(default=0, verbose_name="等级")),
                ("exp", models.IntegerField(default=0, verbose_name="经验值")),
                ("date", models.DateField(verbose_name="生成日期")),
                (
                    "mode_type",
                    models.CharField(blank=True, max_length=254, verbose_name="模型类型"),
                ),
                (
                    "uid",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="login.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "pets infomration by pet_id",
                "verbose_name_plural": "宠物仓",
                "db_table": "pets_info",
                "managed": True,
            },
        ),
    ]
