# Generated by Django 4.1.2 on 2023-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petsinfo",
            name="gender",
            field=models.CharField(blank=True, max_length=12, verbose_name="宠物性别"),
        ),
    ]
