# Generated by Django 4.1.2 on 2023-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0003_petsinfo_p_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="petsinfo",
            name="description",
            field=models.CharField(blank=True, max_length=254, verbose_name="宠物描述"),
        ),
    ]
