# Generated by Django 4.1.2 on 2023-06-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pets", "0007_alter_petsinfo_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petsinfo",
            name="p_avatar",
            field=models.ImageField(null=True, upload_to="", verbose_name="宠物图像"),
        ),
    ]
