# Generated by Django 4.1.2 on 2023-06-14 13:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_userinfo_gender"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinfo",
            old_name="photo",
            new_name="avatar",
        ),
    ]
