# Generated by Django 4.1.2 on 2023-06-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_alter_account_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="avatar",
            field=models.TextField(null=True, verbose_name="用户头像"),
        ),
    ]
