# Generated by Django 4.1.2 on 2023-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0006_alter_userinfo_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="uname",
            field=models.CharField(max_length=30, verbose_name="用户名"),
        ),
    ]
